import type { NextPage } from 'next'
import Head from 'next/head'
import { useCallback } from 'react'
import AaaThree from 'src/three/aaaThree';
// import towerModel from 'public/assets/models/tower.gltf';


const Home: NextPage = () => {

  const canvasWrapper = useCallback((ref: HTMLDivElement) => {
    if (ref) {
      const aaaThree = new AaaThree();
      aaaThree.init(ref);
      aaaThree.animate();
      // aaaThree.makeTower(towerModel)
    }
  }, [])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div ref={canvasWrapper}>

      </div>
    </div>
  )
}

export default Home
